---
title: "Visualization"
subtitle: "Part II"
output: github_document
date: "2022-10-04"
---

```{r setup, include = FALSE}
library(tidyverse)
library(ggridges)
library(patchwork)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

## Load the weather data

```{r, warning=FALSE, message=FALSE}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

weather_df
```
As a starting point, let’s revisit the scatterplot of `tmax` against `tmin` made in Visualization Pt 1.

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5)
```

## Labels

We can add labels using the `labs()` function. 

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) +
  labs(
    x = "Minimum Daily Temp (C)",
    y = "Maximum Daily Temp (C)",
    title = "Scatterplot of daily temp extremes",
    caption = "Data come from the rnoaa package",
    color = "Location"
  )
```


